config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'news#index'

  resources :news

  post 'news/parsing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :news
  validates :news_id, presence: true
end

app/models/news.rb
class News < ApplicationRecord
  has_one :micropost
  default_scope -> {order(time: :desc)}

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  def hello
    render plain: "hello world!"

  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController


end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  before_action :set_news, only: %i[show edit update destroy]
  SITE = "http://4pda.ru"
  # GET /news
  # GET /news.json
  def index
    @news = News.search(params[:search]).paginate(:page => params[:page])
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    @micropost = @news.micropost
  end

  # GET /news/new
  def newcontent
    @news = News.new
  end

  # GET /news/1/edit
  def edit;
  end

  def parsing
    begin
      parse_paginators(1)
    rescue => err
      render plain: err
    end
  end


  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        @micropost = Micropost.create(content: @news.title, url: @news.id, news_id: @news.id)
        format.html {redirect_to @news, notice: 'News was successfully created.'}
        format.json {render :show, status: :created, location: @news}
      else
        format.html {render :new}
        format.json {render json: @news.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html {redirect_to @news, notice: 'News was successfully updated.'}
        format.json {render :show, status: :ok, location: @news}
      else
        format.html {render :edit}
        format.json {render json: @news.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.micropost.destroy
    @news.destroy
    respond_to do |format|
      format.html {redirect_to news_index_url, notice: 'News was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def parse_pages(url)
    posts_array = []
    agent = Mechanize.new
    posts = agent.get(url).search('.post')
    posts.each do |post|
      news = {}
      news[:title] = post.search('.list-post-title').text.downcase
      news[:description] = post.search("[@itemprop='description']").text
      news[:url] = 'http:' + post.search('a/@href').first.to_s
      news[:date] = post.search('meta/@content').text
      news[:img] = post.search('img/@src').text
      posts_array << news unless news[:title].nil?
    end
    posts_array
  end

  def parse_paginators(number)
    agent = Mechanize.new
    page = agent.get(SITE + "/news/page/" + number.to_s)
    current_page = page.search(".active").text.to_i
    next_page = current_page + 1
    puts current_page
    pages = parse_pages(SITE + "/news/page/" + number.to_s)

    pages.each do |h|
      if News.find_by title: h[:title]
      else
        @news = News.create(title: h[:title], time: h[:date], img: h[:img]) if h[:title] != ''
        @micropost = Micropost.create(content: h[:description], url: h[:url], news_id: @news.id) if h[:description] != ''
      end
    end

    #что бы не грузить все страницы раскоментировать 2 строки
    # return current_page unless current_page < 1
    # parse_paginators(next_page)

    if News.find_by time: pages.first[:date]
      current_page
    else
      Thread.new do
        parse_paginators(next_page)
      end
    end

  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = News.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_params
    params.require(:news).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parse4pdaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  <!-- Description, Keywords and Author -->
  <meta name="description" content="Your description">
  <meta name="keywords" content="Your,Keywords">
  <meta name="author" content="ResponsiveWebInc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>


<!-- UI # -->
<div class="ui-198 clearfix">

  <!-- Screenshot -->
  <div class="shot">
    <a href="#"><img src="<%= @news.img %>" alt="" class="img-responsive"/></a>
  </div>

  <!-- Details -->
  <div class="details">

    <!-- Head -->
    <div class="head clearfix">
      <div class="heading">
        <h2><%= @news.title.upcase %></h2>
        <h3><%= @news.time %></h3>
      </div>
    </div>

    <!-- Content -->
    <p><%= @micropost.content %></p>

    <!-- Button -->
    <div class="button">
      <p>Оригинал статьи:
        <a href="<%= @micropost.url %>"><%= @micropost.url %></a>
      </p>
    </div>

    <!-- Contact -->
    <div class="contact">
      <%= link_to 'Назад', news_index_path %>
    </div>

  </div>

</div>

</body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/_news.html.erb
<div class="row news ">
  <% @news.each do |news| %>
    <div class="col-md-3 blog_box">
      <a href="#" class="mask">
        <img src="<%= news.img %>" alt="image" class="img-responsive zoom-img" />
      </a>
      <h3><%= link_to news.title, news %></h3>
      <div class="links">
        <ul>
          <li><span>
               <%=Date.parse news.time %>
          </span></li>
          <li><span>news id: <%= news.id %></span></li>
        </ul>
      </div>
      <%#= link_to news, class: "btn1 btn-8 btn-8c" do %>
<!--        Смотреть-->
      <%# end %>
    </div>
  <% end %>
</div>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<!DOCTYPE html>
<html>

<body>


<div class="container">
  <div class="logo">
    <h1>Новости сайта 4pda.ru</h1>
  </div>
  <br>
  <nav class="navbar navbar-default">
    <div class="container-fluid">

      <%= form_tag news_index_path, :method => 'get', :id => "news_search", :class => "form-group" do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: 'form-control', :placeholder => "Введите заголовок статьи" %>
        </div>
        <%#= submit_tag "Поиск", :title => nil, :class => "btn btn-default" %>
      <% end %>

    </div><!-- /.container-fluid -->
  </nav>


</div>

<div class="container">
  <div class="text-center">
    <%= button_to 'Обновить', news_parsing_path, method: :post, :class => "btn btn-default" %>

    <%= will_paginate(@news, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

  </div>



  <div id="news"><%= render 'news/news' %></div>

  <div class="text-center">
    <%= will_paginate(@news, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

  </div>
</div>
</body>
</html>

app/views/news/index.js.erb
$("#news").html("<%= escape_javascript(render("news")) %>");

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
  <%= render 'microposts/show' %>